[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False

# Явно указываем, что пакеты определяются по структуре директорий
explicit_package_bases = True

# Указываем корень проекта как базу для модулей
mypy_path = .

# Игнорируем отсутствующие импорты для библиотек без stubs
ignore_missing_imports = True

# Исключаем служебные папки
exclude = venv|__pycache__|\.git

# Для библиотек без типов
[mypy-factory.*]
ignore_missing_imports = True

[mypy-flask_sqlalchemy.*]
ignore_missing_imports = True

[mypy.db.*]
ignore_missing_imports = True

